[package]
name = "erp_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
xlsxwriter = "0.6.1"
calamine = "0.19"
